server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
    show-sql: true
  output:
    ansi:
      enabled: always
  oauth:
    naver:
      client_id: hjXAKRZSt03GUwcpKpVm
      client_secret: cOZFIDt4t9
      request-token-uri: http://localhost:8080/api/v1/user/login
      redirect_uri: http://localhost:8080/api/v1/news/getAll

logging:
  level:
    '[com.example.server]': DEBUG
    '[org.hibernate.type]': TRACE


